name: Mike Curran Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7781913271173835
title: Mike Curran Photography - Professional Wedding Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#575757'
    - '#fffffe'
    - '#bfbfbf'
    - '#b47e6c'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
